name: Banka 4 - CI
run-name: Checking if ${{ github.repository }} builds successfully

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build-dev:
    runs-on: ubuntu-latest
    env:
      ENV: development
      COMPOSE_FILE: docker-compose-dev.yml

    steps:
    - name: Check out ${{ github.ref }} after a ${{ github.event_name }} event
      uses: actions/checkout@v5

    - name: Set up environment variables
      run: |
        echo "ENV=${{ env.ENV }}" >> .env
        echo "PORT=${{ vars.PORT }}" >> .env
        echo "DB_HOST=${{ vars.DB_HOST }}" >> .env
        echo "DB_PORT=${{ vars.DB_PORT }}" >> .env
        echo "DB_USER=${{ secrets.DB_USER }}" >> .env
        echo "DB_PASS=${{ secrets.DB_PASS }}" >> .env
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
        echo "SMTP_HOST=${{ secrets.SMTP_HOST }}" >> .env
        echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> .env
        echo "SMTP_USER=${{ secrets.SMTP_USER }}" >> .env
        echo "SMTP_PASS=${{ secrets.SMTP_PASS }}" >> .env
        echo "EMAIL_FROM=${{ vars.EMAIL_FROM }}" >> .env
        echo "FRONTEND_BASE_URL=${{ vars.FRONTEND_BASE_URL }}" >> .env
        echo "BACKEND_BASE_URL=${{ vars.BACKEND_BASE_URL }}" >> .env

    - name: Run the compose file
      run: docker compose -f ${{ env.COMPOSE_FILE }} up -d --build

    - name: Wait for the services to start up and check their health
      run: |
        while docker compose -f ${{ env.COMPOSE_FILE }} ps | grep "starting"; do
          sleep 5
        done
        if docker compose -f ${{ env.COMPOSE_FILE }} ps | grep "unhealthy"; then
          echo "One or more services are unhealthy. Check the logs for details."
          exit 1
        fi

    - name: Print running containers
      if: failure() || success()
      run: docker compose -f ${{ env.COMPOSE_FILE }} ps

    - name: Print container logs
      if: failure() || success()
      run: docker compose -f ${{ env.COMPOSE_FILE }} logs
        
    - name: Bring containers down
      if: failure() || success()
      run: docker compose -f ${{ env.COMPOSE_FILE }} down


  # build-prod:
  #   runs-on: ubuntu-latest
  #   environment: production
  #   steps: